export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      prospects: {
        Row: {
          id: string;
          company_name: string;
          domain: string | null;
          industry: string | null;
          employee_count_range: string | null;
          hq_location: string | null;
          country: string;
          priority_score: number;
          signal_summary: string | null;
          proposed_company_type: string | null;
          proposed_direct_buy_likelihood: string;
          proposed_infra_ownership_verdict: string;
          hardware_categories: string[];
          source: string;
          status: string;
          promoted_account_id: string | null;
          promoted_at: string | null;
          dismissed_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_name: string;
          domain?: string | null;
          industry?: string | null;
          employee_count_range?: string | null;
          hq_location?: string | null;
          country?: string;
          priority_score?: number;
          signal_summary?: string | null;
          proposed_company_type?: string | null;
          proposed_direct_buy_likelihood?: string;
          proposed_infra_ownership_verdict?: string;
          hardware_categories?: string[];
          source?: string;
          status?: string;
          promoted_account_id?: string | null;
          promoted_at?: string | null;
          dismissed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_name?: string;
          domain?: string | null;
          industry?: string | null;
          employee_count_range?: string | null;
          hq_location?: string | null;
          country?: string;
          priority_score?: number;
          signal_summary?: string | null;
          proposed_company_type?: string | null;
          proposed_direct_buy_likelihood?: string;
          proposed_infra_ownership_verdict?: string;
          hardware_categories?: string[];
          source?: string;
          status?: string;
          promoted_account_id?: string | null;
          promoted_at?: string | null;
          dismissed_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      accounts: {
        Row: {
          id: string;
          company_name: string;
          domain: string | null;
          website: string | null;
          linkedin_company_url: string | null;
          industry: string | null;
          employee_count_range: string | null;
          hq_location: string | null;
          country: string;
          company_type: string;
          status: string;
          direct_buy_likelihood: string;
          infra_ownership_verdict: string;
          evidence_strength: string;
          why_it_matters: string | null;
          negative_signals: string | null;
          component_fit: Json;
          hardware_categories: string[];
          notes: string | null;
          source_prospect_id: string | null;
          last_reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_name: string;
          domain?: string | null;
          website?: string | null;
          linkedin_company_url?: string | null;
          industry?: string | null;
          employee_count_range?: string | null;
          hq_location?: string | null;
          country?: string;
          company_type?: string;
          status?: string;
          direct_buy_likelihood?: string;
          infra_ownership_verdict?: string;
          evidence_strength?: string;
          why_it_matters?: string | null;
          negative_signals?: string | null;
          component_fit?: Json;
          hardware_categories?: string[];
          notes?: string | null;
          source_prospect_id?: string | null;
          last_reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_name?: string;
          domain?: string | null;
          website?: string | null;
          linkedin_company_url?: string | null;
          industry?: string | null;
          employee_count_range?: string | null;
          hq_location?: string | null;
          country?: string;
          company_type?: string;
          status?: string;
          direct_buy_likelihood?: string;
          infra_ownership_verdict?: string;
          evidence_strength?: string;
          why_it_matters?: string | null;
          negative_signals?: string | null;
          component_fit?: Json;
          hardware_categories?: string[];
          notes?: string | null;
          source_prospect_id?: string | null;
          last_reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          account_id: string;
          full_name: string;
          first_name: string;
          last_name: string;
          email: string | null;
          email_confidence: string;
          email_pattern: string | null;
          phone: string | null;
          title: string | null;
          department: string;
          seniority_tier: string;
          role_category: string;
          likely_manages: string | null;
          why_relevant: string | null;
          likely_works_with: string | null;
          linkedin_url: string | null;
          contact_priority: string;
          outreach_status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          full_name: string;
          first_name: string;
          last_name: string;
          email?: string | null;
          email_confidence?: string;
          email_pattern?: string | null;
          phone?: string | null;
          title?: string | null;
          department?: string;
          seniority_tier?: string;
          role_category?: string;
          likely_manages?: string | null;
          why_relevant?: string | null;
          likely_works_with?: string | null;
          linkedin_url?: string | null;
          contact_priority?: string;
          outreach_status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          email?: string | null;
          email_confidence?: string;
          email_pattern?: string | null;
          phone?: string | null;
          title?: string | null;
          department?: string;
          seniority_tier?: string;
          role_category?: string;
          likely_manages?: string | null;
          why_relevant?: string | null;
          likely_works_with?: string | null;
          linkedin_url?: string | null;
          contact_priority?: string;
          outreach_status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      evidence: {
        Row: {
          id: string;
          account_id: string;
          headline: string;
          description: string;
          raw_excerpt: string | null;
          source_url: string | null;
          source_type: string;
          signal_direction: string;
          signal_category: string;
          reliability_score: number;
          hardware_categories: string[];
          detected_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          headline: string;
          description: string;
          raw_excerpt?: string | null;
          source_url?: string | null;
          source_type: string;
          signal_direction?: string;
          signal_category?: string;
          reliability_score?: number;
          hardware_categories?: string[];
          detected_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          headline?: string;
          description?: string;
          raw_excerpt?: string | null;
          source_url?: string | null;
          source_type?: string;
          signal_direction?: string;
          signal_category?: string;
          reliability_score?: number;
          hardware_categories?: string[];
          detected_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      news_items: {
        Row: {
          id: string;
          title: string;
          summary: string;
          source_url: string;
          source_name: string;
          published_at: string;
          event_type: string;
          urgency_score: number;
          commercial_relevance_score: number;
          confidence_score: number;
          impact_summary: string;
          recommended_outreach_department: string | null;
          suggested_outreach_angle: string | null;
          component_impact: Json;
          hardware_categories: string[];
          account_id: string | null;
          linked_accounts: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          summary: string;
          source_url: string;
          source_name: string;
          published_at: string;
          event_type?: string;
          urgency_score?: number;
          commercial_relevance_score?: number;
          confidence_score?: number;
          impact_summary: string;
          recommended_outreach_department?: string | null;
          suggested_outreach_angle?: string | null;
          component_impact?: Json;
          hardware_categories?: string[];
          account_id?: string | null;
          linked_accounts?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          summary?: string;
          source_url?: string;
          source_name?: string;
          published_at?: string;
          event_type?: string;
          urgency_score?: number;
          commercial_relevance_score?: number;
          confidence_score?: number;
          impact_summary?: string;
          recommended_outreach_department?: string | null;
          suggested_outreach_angle?: string | null;
          component_impact?: Json;
          hardware_categories?: string[];
          account_id?: string | null;
          linked_accounts?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      feed_sources: {
        Row: {
          id: string;
          name: string;
          url: string;
          source_type: string;
          is_enabled: boolean;
          last_fetched_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          url: string;
          source_type?: string;
          is_enabled?: boolean;
          last_fetched_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          url?: string;
          source_type?: string;
          is_enabled?: boolean;
          last_fetched_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_runs: {
        Row: {
          id: string;
          agent_name: string;
          status: string;
          started_at: string;
          completed_at: string | null;
          duration_ms: number | null;
          summary: Json;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent_name: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          summary?: Json;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent_name?: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          summary?: Json;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      discovery_sources: {
        Row: {
          id: string;
          name: string;
          source_type: string;
          source_key: string | null;
          is_enabled: boolean;
          record_count: number | null;
          last_run_at: string | null;
          last_run_job_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          source_type: string;
          source_key?: string | null;
          is_enabled?: boolean;
          record_count?: number | null;
          last_run_at?: string | null;
          last_run_job_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          source_type?: string;
          source_key?: string | null;
          is_enabled?: boolean;
          record_count?: number | null;
          last_run_at?: string | null;
          last_run_job_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      component_lookups: {
        Row: {
          id: string;
          part_number: string;
          manufacturer: string | null;
          description: string | null;
          category: string | null;
          subcategory: string | null;
          socket_platform: string | null;
          ecosystem: string | null;
          specs: Json;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          part_number: string;
          manufacturer?: string | null;
          description?: string | null;
          category?: string | null;
          subcategory?: string | null;
          socket_platform?: string | null;
          ecosystem?: string | null;
          specs?: Json;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          part_number?: string;
          manufacturer?: string | null;
          description?: string | null;
          category?: string | null;
          subcategory?: string | null;
          socket_platform?: string | null;
          ecosystem?: string | null;
          specs?: Json;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      account_hardware_prefs: {
        Row: {
          id: string;
          account_id: string;
          buys_cpus: boolean;
          buys_gpus: boolean;
          buys_memory: boolean;
          buys_ssds: boolean;
          buys_networking: boolean;
          buys_systems: boolean;
          buys_frus: boolean;
          cpu_ecosystem: string[];
          gpu_ecosystem: string[];
          platforms: string[];
          account_type: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          buys_cpus?: boolean;
          buys_gpus?: boolean;
          buys_memory?: boolean;
          buys_ssds?: boolean;
          buys_networking?: boolean;
          buys_systems?: boolean;
          buys_frus?: boolean;
          cpu_ecosystem?: string[];
          gpu_ecosystem?: string[];
          platforms?: string[];
          account_type?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          buys_cpus?: boolean;
          buys_gpus?: boolean;
          buys_memory?: boolean;
          buys_ssds?: boolean;
          buys_networking?: boolean;
          buys_systems?: boolean;
          buys_frus?: boolean;
          cpu_ecosystem?: string[];
          gpu_ecosystem?: string[];
          platforms?: string[];
          account_type?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      deal_history: {
        Row: {
          id: string;
          account_id: string;
          part_number: string;
          manufacturer: string | null;
          description: string | null;
          quantity: number | null;
          direction: string;
          deal_date: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          part_number: string;
          manufacturer?: string | null;
          description?: string | null;
          quantity?: number | null;
          direction: string;
          deal_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string;
          part_number?: string;
          manufacturer?: string | null;
          description?: string | null;
          quantity?: number | null;
          direction?: string;
          deal_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      discovery_log: {
        Row: {
          id: string;
          company_name: string;
          search_type: string | null;
          state: string | null;
          discovered_at: string;
          added_to_accounts: boolean;
          job_run_id: string | null;
        };
        Insert: {
          id?: string;
          company_name: string;
          search_type?: string | null;
          state?: string | null;
          discovered_at?: string;
          added_to_accounts?: boolean;
          job_run_id?: string | null;
        };
        Update: {
          id?: string;
          company_name?: string;
          search_type?: string | null;
          state?: string | null;
          discovered_at?: string;
          added_to_accounts?: boolean;
          job_run_id?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
